# docker-compose.yml
version: '3.8'

services:
  trading-bot:
    build: .
    container_name: eurusd_trading_bot
    restart: unless-stopped
    environment:
      - TRADING_MODE=live
      - TRADING_LOGIN=${TRADING_LOGIN}
      - TRADING_PASSWORD=${TRADING_PASSWORD}
      - TRADING_WEB_API_TOKEN_ID=${TRADING_WEB_API_TOKEN_ID}
      - TRADING_WEB_API_TOKEN_KEY=${TRADING_WEB_API_TOKEN_KEY}
      - TRADING_WEB_API_TOKEN_SECRET=${TRADING_WEB_API_TOKEN_SECRET}
      - REDIS_HOST=redis
      - TZ=UTC
      - APP_BASE_DIR=/app
      - TRADING_PARQUET_PATH=/app/data/ticks
      - TRADING_SQLITE_PATH=/app/data/strategy_meta.db
      - TRADING_MODELS_PATH=/app/models
      - TRADING_LOG_PATH=/app/logs
      - TRADING_DATA_DIR=/app/data
      - TRADING_LOG_DIR=/app/logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    ports:
      - "9090:9090"
    depends_on:
      - redis
    networks:
      - trading-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  redis:
    image: redis:7-alpine
    container_name: trading_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - trading-network

  prometheus:
    image: prom/prometheus:latest
    container_name: trading_prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - "9091:9090"
    networks:
      - trading-network

  grafana:
    image: grafana/grafana:latest
    container_name: trading_grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - trading-network

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: trading_jupyter
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-yoursecuretoken}
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data:ro
    ports:
      - "8888:8888"
    networks:
      - trading-network
    profiles:
      - analysis

networks:
  trading-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data: